// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0mlgBmygYAlKbfvAhk4u-1CXdUY8JerE',
    appId: '1:1075752615745:web:9d4f9b8023e869e6c76bc0',
    messagingSenderId: '1075752615745',
    projectId: 'flutterfinancas',
    authDomain: 'flutterfinancas.firebaseapp.com',
    storageBucket: 'flutterfinancas.appspot.com',
    measurementId: 'G-1ZJY2JKWLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBncU0GygEavuk5yiXLQ40BoaJXoeXLTM',
    appId: '1:1075752615745:android:c8f7a7a64c7959cbc76bc0',
    messagingSenderId: '1075752615745',
    projectId: 'flutterfinancas',
    storageBucket: 'flutterfinancas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2mpnnr_i2DWD9jObggIOCun-HwP0rX1o',
    appId: '1:1075752615745:ios:f9f6f6544449a6bdc76bc0',
    messagingSenderId: '1075752615745',
    projectId: 'flutterfinancas',
    storageBucket: 'flutterfinancas.appspot.com',
    iosBundleId: 'com.example.flutterFinancas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2mpnnr_i2DWD9jObggIOCun-HwP0rX1o',
    appId: '1:1075752615745:ios:f9f6f6544449a6bdc76bc0',
    messagingSenderId: '1075752615745',
    projectId: 'flutterfinancas',
    storageBucket: 'flutterfinancas.appspot.com',
    iosBundleId: 'com.example.flutterFinancas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0mlgBmygYAlKbfvAhk4u-1CXdUY8JerE',
    appId: '1:1075752615745:web:a383b4c16fd539c1c76bc0',
    messagingSenderId: '1075752615745',
    projectId: 'flutterfinancas',
    authDomain: 'flutterfinancas.firebaseapp.com',
    storageBucket: 'flutterfinancas.appspot.com',
    measurementId: 'G-3YZBM14BJD',
  );

}